FROM node:20-alpine

WORKDIR /app
RUN chown node /app
USER node

COPY --chown=node:node ./package.json ./package.json
COPY --chown=node:node ./.npmrc ./.npmrc

ARG NPM_TOKEN
ENV NPM_TOKEN=$NPM_TOKEN

RUN npm i --ignore-scripts

COPY --chown=node:node ./public ./public
COPY --chown=node:node ./src ./src
COPY --chown=node:node ./approot.ts ./approot.ts
COPY --chown=node:node ./vite.config.ts ./vite.config.ts
COPY --chown=node:node ./tsconfig.json ./tsconfig.json

RUN npm run build

EXPOSE 8000

ENV NODE_ENV=production
ENV APP_HOST=0.0.0.0

CMD ["node", "dist/app.js"] 
